repos:
  - repo: https://gitlab.com/smop/pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: check-poetry
  - repo: https://github.com/twu/skjold
    rev: v0.1.5
    hooks:
      - id: skjold
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
      - id: black
        name: black
        entry: poetry run black
        language: system
        files: ".py$"
      - id: blacken-docs
        name: blacken-docs
        entry: poetry run blacken-docs
        language: system
